# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache {H:/Semester 7/CA/Lab/Lab11/fpga/docs/procssor_vivado/.Xil/Vivado-12888-DESKTOP-FD2K84H/incrSyn}
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {H:/Semester 7/CA/Lab/Lab11/fpga/docs/procssor_vivado/procssor_vivado.cache/wt} [current_project]
set_property parent.project_path {H:/Semester 7/CA/Lab/Lab11/fpga/docs/procssor_vivado/procssor_vivado.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {h:/Semester 7/CA/Lab/Lab11/fpga/docs/procssor_vivado/procssor_vivado.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {{H:/Semester 7/CA/Lab/Lab11/fpga/sim/machine_codes.mem}}
read_verilog -library xil_defaultlib -sv {
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/adder.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/alu_decoder.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/alu_new.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/uart/baud_counter.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/uart/bit_counter.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/branch_checker.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/clock_div.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/csr_decoder.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/csr_ops.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/csr_regs.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/data_mem.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/riscv_pkg.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/forwarding_unit.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/imm_generator.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/inst_mem.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/lsu.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/main_decoder.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/mux_2x1.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/mux_4x1.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/pc.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/peripherals_bus.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/pipeline_reg_1.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/pipeline_reg_2.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/reg_file.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/uart/shift_register.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/ssd.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/uart/uart_fsm.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/uart/uart_riscv_contr.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/uart/uart_tx.sv}
  {H:/Semester 7/CA/Lab/Lab11/fpga/rtl/riscv_pipelined_top.sv}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{H:/Semester 7/CA/Lab/Lab11/fpga/docs/procssor_vivado/procssor_vivado.srcs/constrs_1/new/constraints_processor.xdc}}
set_property used_in_implementation false [get_files {{H:/Semester 7/CA/Lab/Lab11/fpga/docs/procssor_vivado/procssor_vivado.srcs/constrs_1/new/constraints_processor.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top riscv_pipelined_top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef riscv_pipelined_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file riscv_pipelined_top_utilization_synth.rpt -pb riscv_pipelined_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
